# Generated by Django 3.2.6 on 2021-12-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211207_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Total_items',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
